apiVersion: apps/v1
kind: Deployment

metadata:
  name: ledger-api
  namespace: payments
  labels:
    app: ledger-api

spec:

  # Running Multiple replicas for availability and zero downtime
  replicas: 3

  selector:
    matchLabels:
      app: ledger-api

  template:

    metadata:
      labels:
        app: ledger-api

    spec:

      # Using a separate ServiceAccount instead of default account
      serviceAccountName: ledger-api-sa


      # Pod level security context
      # Required by Kyverno non-root policy
      securityContext:

        # Pod cannot run as root
        runAsNonRoot: true

        # Normal Linux user
        runAsUser: 1000

        # Normal Linux group
        runAsGroup: 1000


      containers:

        - name: ledger-api

          # Application image
          image: ghcr.io/azmiabadpy/ledger-api:main

          # Use local image if available
          imagePullPolicy: IfNotPresent


          ports:

            - containerPort: 8080


          env:


            # Application configuration from ConfigMap
            - name: APP_PORT

              valueFrom:

                configMapKeyRef:

                  name: ledger-api-config

                  key: APP_PORT



            # Sensitive values from SealedSecret
            - name: STRIPE_API_KEY

              valueFrom:

                secretKeyRef:

                  name: ledger-api-secret

                  key: STRIPE_API_KEY



            - name: DB_PASSWORD

              valueFrom:

                secretKeyRef:

                  name: ledger-api-secret

                  key: DB_PASSWORD



          # Container level security hardening
          securityContext:


            # Prevent root execution
            runAsNonRoot: true

            runAsUser: 1000

            runAsGroup: 1000


            # Prevent privilege escalation
            allowPrivilegeEscalation: false


            # Immutable filesystem
            readOnlyRootFilesystem: true


            # Remove unnecessary Linux capabilities
            capabilities:

              drop:

                - ALL


            # Kubernetes default seccomp profile
            seccompProfile:

              type: RuntimeDefault



          resources:


            requests:

              cpu: "100m"

              memory: "128Mi"



            limits:

              cpu: "500m"

              memory: "256Mi"



          # Container health check
          livenessProbe:


            httpGet:

              path: /health

              port: 8080


            initialDelaySeconds: 10

            periodSeconds: 10



          # Traffic only after application is ready
          readinessProbe:


            httpGet:

              path: /health

              port: 8080


            initialDelaySeconds: 5

            periodSeconds: 5
