---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgB7TPRMyIE3sisAJf7/gqVaBMoLHHqlCmlu3W5O0qmfrub6YvnHSQTmc2S1tII7I6k0o0CVCQU1mdSG6eoe8fjgUwg4X8IMnVjFEU95ejl4VAqxqEywkHU8ekYVIl2YfEEeyJVIRbTWZfef0S2FjNtC156pczXJLcFPDYPzcLteouD8YT47pNZhgdmrAfQqvnKL80zHrSlG7lGcNzhA2snMkNbHgtRJs2/AnWGTYK4WGwyHTMUCYTeRNyLAnQ9OYZmFu3k00K/lI7gyVOIWcPrOAea1NBoP/WRFE6EnnLwS9kQpKFX4b19P2mrJEYNugM7XUH7VqtY9vtjJjZLcOXCZMi6I72MbkNSm3yW5X6bGSDs5JrpnRVm6lsmoWIvdD3DRx8FpUGhkKexqpgM7DiPckadT4XN3/0ghylD67ybtkfH043dZTzzVIzJJzZh66AihiO0TRW1o9baJjAx+8aZz6kuBxuZUGvfkXVq6eSItZ+axXjh5BrueXnWzFm+aGFsDtrivQQKK96vF44Ej7vBHDBebrN43XWWBdb79PqDHm3XnPUf7k45xtzLJwl9qyLE5GB2oAEmNzkeBNG11wTDYCs/NlhGSbMP4QB2ICqfZLLtleMN8YtoX3oGnNXXJoY+twB3cPZsAhfoY53SI0rGdqIubONKvTxamsTleC0NCqeQnV8nzO2iFsQwjiGM6hOZ+OTue9Cui6cawBQ==
    STRIPE_API_KEY: AgADUzOElH45liD/xQYOQ2Na05sTVSIA6fIzlpRKPoY6FxiJ1iSI0dE7iQ8RJtNr/cLi2t+71pMXUVUfAOEphoEJBZaVy7IYMsYM9FniVbOUFWNVTDX5f1dz1jkBUMBZLof6eWlujIb9YGt1frLd0x40vI0Pi49gpgeY20T4+8EYzykJI/32XG62mvAJpm+PSMErBxwSoyBas3ZjuVKCbBOKSFwVOLm2z+vXnyiEZMaJ0/llTHXnAr95wUA3SLWoJtkxoL7orfXTphxNEyP57eFFh0OItPTX5fFv7Qxwaho3H0MFfKuzchFrjP6Mio/Vh4USm4OecMTYxhpqUTmw5+rSq8KX6D5uSTydRwDEICoNgzkORU9qyWmjjhiXInIw8Uyv7qXTwKbuQ5fkmE4s5kaTx7rIdqb/PLgVmQrACnTIJXAbAudfhAdMujNENZarJIbjmIDp53SMIcz3XwiZwiPTK1vRvGo+Rsc7GP/DIThyJsXsnEOct8onav7e6fGYDj53awmiX3JAEPC0CMRmyMRbVhXcK8nCHSyAYvmrQD6YAh2+HRFcu19GWiaGDffn+poRjZJoJJLrrI/J9FcG0PTvYbAgMPgndyq/iao2B8nO7WInd9s3yoxZfM4cIq4rEMCzsSMZ9vcGUqPI3iTGJJ10khtmLFAX+qOMLCpNc9WFHJiPEj+BG6PL4eOWUrPWihGhduqVEQDshCr/1TBaC+RYjqbXYydDiG7jqqR8ZA==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
