apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: verify-image-signature

spec:

  validationFailureAction: Enforce

  rules:

    - name: verify-image

      match:

        any:
          - resources:

              kinds:
                - Pod


      # Exclude reporting helper pod
      exclude:

        any:

          - resources:

              namespaces:
                - payments

              selector:

                matchLabels:

                  app: reporting



      verifyImages:

        - imageReferences:

            # Only verify application images
            - "ghcr.io/azmiabadpy/ledger-api*"


          required: true

          mutateDigest: true

          verifyDigest: true
