name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write
  attestations: write


env:
  IMAGE_NAME: ledger-api


jobs:

  security-and-build:

    name: Build, Scan, Sign and Push

    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4



      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3



      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}



      - name: Run Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Run Semgrep SAST Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: auto



      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1



      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ledger-api
          tags: |
            type=sha



      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          load: true
          push: false
          tags: ledger-api:test



      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ledger-api:test
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1



      - name: Push Docker Image to GHCR
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ledger-api:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}



      - name: Install Cosign
        uses: sigstore/cosign-installer@v3



      - name: Sign Docker Image with Cosign
        run: |

          cosign sign --yes \
          ghcr.io/${{ github.repository_owner }}/ledger-api@${{ steps.push.outputs.digest }}



      - name: Verify Signature
        run: |
          cosign verify \
            --certificate-identity-regexp="https://github.com/${{ github.repository }}/.github/workflows/.*" \
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
            ghcr.io/${{ github.repository_owner }}/ledger-api@${{ steps.push.outputs.digest }}



      - name: Generate SLSA Provenance Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/ledger-api
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
